version: '3.7'
services:
  localstack-s3:
    image: localstack/localstack:latest
    container_name: localstack-sts
    environment:
     - SERVICES=sts:4566
     - DEFAULT_REGION=us-east-1
     - DATA_DIR=/tmp/localstack/data
    ports:
     - "4566:4566"
    volumes:
      - localstack-data:/tmp/localstack
volumes:
  localstack-data:
    name: localstack-data