version: '3.7'
services:
  localstack-dynamodb :
    image: localstack/localstack:latest
    container_name: localstack-dynamodb
    environment:
     - SERVICES=dynamodb:4564
     - DEFAULT_REGION=us-west-2
     - DATA_DIR=/tmp/localstack/data
    ports:
     - "8000:4564"
    volumes:
      - localstack-data:/tmp/localstack
volumes:
  localstack-data:
    name: localstack-data